# Generated by Django 5.2.4 on 2026-09-03 15:58

import django.db.models.deletion
import main.models.order
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Ikonka')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(help_text='+998XXXXXXXXX formatida', max_length=13, unique=True, verbose_name='Telefon raqam')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name="To'liq ism")),
                ('role', models.CharField(choices=[('client', 'Mijoz'), ('admin', 'Admin')], default='client', max_length=10, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('tashkent_city', 'Toshkent shahri'), ('tashkent_region', 'Toshkent viloyati'), ('samarkand', 'Samarqand'), ('bukhara', 'Buxoro'), ('namangan', 'Namangan'), ('andijan', 'Andijon'), ('fergana', "Farg''ona"), ('kashkadarya', 'Qashqadaryo'), ('surkhandarya', 'Surxondaryo'), ('syrdarya', 'Sirdaryo'), ('jizzakh', 'Jizzax'), ('navoi', 'Navoiy'), ('khorezm', 'Xorazm'), ('karakalpakstan', "Qoraqalpog''iston")], max_length=20, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar / tuman')),
                ('street', models.CharField(max_length=200, verbose_name="Ko''cha")),
                ('house_number', models.CharField(max_length=20, verbose_name='Uy raqami')),
                ('apartment', models.CharField(blank=True, default='', max_length=20, verbose_name='Xonadon (ixtiyoriy)')),
                ('full_address', models.TextField(help_text="Yetkazib beruvchi uchun qo''shimcha ma''lumot (mo''ljal, qavat, va boshqalar)", verbose_name="To''liq aniq manzil")),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=main.models.order.generate_order_number, max_length=10, unique=True, verbose_name='Buyurtma raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Tayyorlanmoqda'), ('shipped', "Yo''lda"), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=15, verbose_name='Holat')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami (chegirmasiz)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Yetkazib berish narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy summa')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.address', verbose_name='Yetkazib berish manzili')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('material', models.CharField(blank=True, choices=[('aluminium', 'Alyuminiy'), ('pvc', 'PVX (Plastik)'), ('wood', "Yog''och"), ('steel', "Po''lat")], max_length=20, verbose_name='Material')),
                ('design_style', models.CharField(blank=True, choices=[('modern', 'Zamonaviy'), ('classic', 'Klassik'), ('minimalist', 'Minimalist')], max_length=20, verbose_name='Dizayn uslubi')),
                ('base_price', models.DecimalField(decimal_places=2, help_text="Kv.m uchun narx yoki qat'iy narx", max_digits=12, verbose_name='Asosiy narx (UZS)')),
                ('price_type', models.CharField(choices=[('per_sqm', 'Kv.m uchun'), ('fixed', "Qat'iy narx")], default='per_sqm', max_length=10, verbose_name='Narx turi')),
                ('badge', models.CharField(blank=True, choices=[('new', 'Yangi'), ('warm', 'Iliq-issiq'), ('sale', 'Sotuvda')], default='', max_length=10, verbose_name='Badge (yorliq)')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('sale', 'Aksiya'), ('out_of_stock', 'Mavjud emas')], default='active', max_length=15, verbose_name='Holat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('profile_thickness', models.CharField(blank=True, max_length=20, verbose_name='Profil qalinligi (mm)')),
                ('max_glass', models.CharField(blank=True, max_length=20, verbose_name='Max shisha (mm)')),
                ('sound_insulation', models.CharField(blank=True, max_length=20, verbose_name='Tovush izolyatsiyasi (dB)')),
                ('climate_resistance', models.TextField(blank=True, verbose_name='Iqlim chidamliligi')),
                ('delivery_info', models.TextField(blank=True, verbose_name="Yetkazib berish ma''lumoti")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi (snapshot)')),
                ('color_name', models.CharField(blank=True, max_length=60, verbose_name='Rang (snapshot)')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Rang HEX (snapshot)')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Kenglik (mm)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='Balandlik (mm)')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Miqdori')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi (snapshot)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jami narxi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='main.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Rang nomi')),
                ('hex_code', models.CharField(blank=True, help_text='#RRGGBB formatida', max_length=7, verbose_name='HEX kodi')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='0 = asosiy narx, musbat = qimmatroq, manfiy = arzonroq', max_digits=12, verbose_name='Narx farqi (UZS)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rangi',
                'verbose_name_plural': 'Mahsulot ranglari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Kenglik (mm)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='Balandlik (mm)')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Miqdori')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.cart', verbose_name='Savat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='main.product', verbose_name='Mahsulot')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='main.productcolor', verbose_name='Rang')),
            ],
            options={
                'verbose_name': 'Savat elementi',
                'verbose_name_plural': 'Savat elementlari',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['-is_main', 'order'],
            },
        ),
    ]
