# Generated by Django 5.2.4 on 2026-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Pastki sarlavha (ixtiyoriy)')),
                ('button_text', models.CharField(blank=True, default='', help_text="Masalan: Katalogni ko'rish", max_length=50, verbose_name='Tugma matni')),
                ('button_url', models.CharField(blank=True, default='', help_text='Masalan: /catalog yoki https://...', max_length=200, verbose_name='Tugma havolasi')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_main', models.CharField(blank=True, default='', help_text='+998712345678', max_length=20, verbose_name='Asosiy telefon')),
                ('phone_whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp raqam')),
                ('phone_extra', models.CharField(blank=True, default='', max_length=20, verbose_name="Qo'shimcha telefon (ixtiyoriy)")),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Manzil')),
                ('work_hours', models.CharField(blank=True, default='', help_text='Masalan: Du-Sh 9:00-18:00', max_length=100, verbose_name='Ish vaqti')),
                ('telegram_url', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='YouTube')),
                ('footer_about', models.TextField(blank=True, default='', help_text='Footer uchun qisqa kompaniya tavsifi', verbose_name='Footer haqida matni')),
                ('footer_copyright', models.CharField(blank=True, default='', help_text='Masalan: 2024 Saramax. Barcha huquqlar himoyalangan.', max_length=200, verbose_name='Copyright matni')),
                ('site_title', models.CharField(blank=True, default='Saramax', max_length=100, verbose_name='Sayt nomi (SEO title)')),
                ('site_description', models.TextField(blank=True, default='', verbose_name='Sayt tavsifi (SEO meta description)')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='settings/og/', verbose_name='OG rasm (ijtimoiy tarmoqlar uchun)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
