# Generated by Django 5.0.6 on 2026-09-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_location',
            field=models.CharField(blank=True, default='', help_text="Google Maps'da qidirish uchun aniq manzil yoki koordinata", max_length=500, verbose_name='Xarita manzili (Google Maps)'),
        ),
    ]
