# Generated by Django 5.0.6 on 2026-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings_map_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Saramax haqida', max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, default='Sifatli va ishonchli mahsulotlar yetkazib beruvchisi', max_length=300, verbose_name='Qisqa izoh / Shior')),
                ('content', models.TextField(default="Saramax — har bir mijoz uchun ishonchli, hamyonbop va eng sifatli mahsulotlarni taqdim etishni o'z oldiga maqsad qilgan zamonaviy do'kon. Bizning asosiy ustuvorligimiz — mijozlarimizga tezkor va a'lo darajadagi xizmat ko'rsatishdir.", verbose_name='Asosiy matn / Kompaniya haqida')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name="Kompaniya / Do'kon rasmi")),
                ('experience_years', models.CharField(blank=True, default='5+', max_length=50, verbose_name="Tajriba ko'rsatkichi (masalan: 5+ yil)")),
                ('stat_1_number', models.CharField(blank=True, default='1000+', max_length=50, verbose_name='Statistika 1 raqam')),
                ('stat_1_label', models.CharField(blank=True, default='Mahsulot turlari', max_length=100, verbose_name='Statistika 1 nomi')),
                ('stat_2_number', models.CharField(blank=True, default='10,000+', max_length=50, verbose_name='Statistika 2 raqam')),
                ('stat_2_label', models.CharField(blank=True, default='Mamnun mijozlar', max_length=100, verbose_name='Statistika 2 nomi')),
                ('stat_3_number', models.CharField(blank=True, default='100%', max_length=50, verbose_name='Statistika 3 raqam')),
                ('stat_3_label', models.CharField(blank=True, default='Sifat kafolati', max_length=100, verbose_name='Statistika 3 nomi')),
                ('stat_4_number', models.CharField(blank=True, default='24/7', max_length=50, verbose_name='Statistika 4 raqam')),
                ('stat_4_label', models.CharField(blank=True, default="Qo'llab-quvvatlash", max_length=100, verbose_name='Statistika 4 nomi')),
                ('mission', models.TextField(blank=True, default="Biz mijozlarimizning ehtiyojlarini chuqur tushunib, bozordagi eng so'nggi va talabgir mahsulotlarni doimiy ravishda taqdim etamiz.", verbose_name='Bizning missiyamiz')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biz haqimizda sahifasi',
                'verbose_name_plural': 'Biz haqimizda sahifasi',
            },
        ),
    ]
